language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  email: false
  irc:
    channels:
      - "irc.spi.gt#techcable"
script: ./gradlew clean build --stacktrace -PrunSlowTests=true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
